<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Krypton.Docking" Version="90.24.11.317" />
    <PackageReference Include="Krypton.Navigator" Version="90.24.11.317" />
    <PackageReference Include="Krypton.Ribbon" Version="90.24.11.317" />
    <PackageReference Include="Krypton.Toolkit" Version="90.24.11.317" />
    <PackageReference Include="Krypton.Workspace" Version="90.24.11.317" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Dames_Scan31_FabienLetouzey\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Update="Resources\CadreGrisSansPriseTransparent.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <Content Include="Resources\DameBlanche.png" />
    <Content Include="Resources\DameNoire.png" />
  </ItemGroup>
</Project>